/*
⚠️ Do not edit this file
*/

import { setDefaults } from './helper';
console.log('✏️ - Database created.');
import speakers from '../db/speakers.json';
import talks from '../db/talks.json';

async function seedDatabase() {
  console.log('💣 - Setting defaults.');
  setDefaults(speakers, talks);
  console.log('💾 - Speakers and talks have been uploaded.');
  console.log('🎉 - Work done, enjoy 🍦');
}

seedDatabase();
